package com.sinyd.allen.service.webserviceclient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2013-02-26T12:53:39.438+08:00
 * Generated source version: 2.5.1
 * 
 */
@WebServiceClient(name = "TestWebService", 
                  wsdlLocation = "http://192.168.1.188/TestWebService/TestWebService.asmx?WSDL",
                  targetNamespace = "http://www.sinyd.com/") 
public class TestWebService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.sinyd.com/", "TestWebService");
    public final static QName TestWebServiceSoap12 = new QName("http://www.sinyd.com/", "TestWebServiceSoap12");
    public final static QName TestWebServiceSoap = new QName("http://www.sinyd.com/", "TestWebServiceSoap");
    static {
        URL url = null;
        try {
            url = new URL("http://192.168.1.188/TestWebService/TestWebService.asmx?WSDL");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(TestWebService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://192.168.1.188/TestWebService/TestWebService.asmx?WSDL");
        }
        WSDL_LOCATION = url;
    }

    public TestWebService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TestWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TestWebService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns TestWebServiceSoap
     */
    @WebEndpoint(name = "TestWebServiceSoap12")
    public TestWebServiceSoap getTestWebServiceSoap12() {
        return super.getPort(TestWebServiceSoap12, TestWebServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TestWebServiceSoap
     */
    @WebEndpoint(name = "TestWebServiceSoap12")
    public TestWebServiceSoap getTestWebServiceSoap12(WebServiceFeature... features) {
        return super.getPort(TestWebServiceSoap12, TestWebServiceSoap.class, features);
    }
    /**
     *
     * @return
     *     returns TestWebServiceSoap
     */
    @WebEndpoint(name = "TestWebServiceSoap")
    public TestWebServiceSoap getTestWebServiceSoap() {
        return super.getPort(TestWebServiceSoap, TestWebServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TestWebServiceSoap
     */
    @WebEndpoint(name = "TestWebServiceSoap")
    public TestWebServiceSoap getTestWebServiceSoap(WebServiceFeature... features) {
        return super.getPort(TestWebServiceSoap, TestWebServiceSoap.class, features);
    }

}
