package com.sinyd.allen.service.webserviceclient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2013-02-26T12:53:39.309+08:00
 * Generated source version: 2.5.1
 * 
 */
@WebService(targetNamespace = "http://www.sinyd.com/", name = "TestWebServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface TestWebServiceSoap {

    @WebResult(name = "HelloWorldResult", targetNamespace = "http://www.sinyd.com/")
    @RequestWrapper(localName = "HelloWorld", targetNamespace = "http://www.sinyd.com/", className = "com.sinyd.allen.service.webserviceclient.HelloWorld")
    @WebMethod(operationName = "HelloWorld", action = "http://www.sinyd.com/HelloWorld")
    @ResponseWrapper(localName = "HelloWorldResponse", targetNamespace = "http://www.sinyd.com/", className = "com.sinyd.allen.service.webserviceclient.HelloWorldResponse")
    public java.lang.String helloWorld(
        @WebParam(name = "name", targetNamespace = "http://www.sinyd.com/")
        java.lang.String name,
        @WebParam(name = "sex", targetNamespace = "http://www.sinyd.com/")
        java.lang.String sex
    );
}
