
package com.zxtech.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BdxService", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://183.129.144.67:8017/BdxWebService/BdxService.asmx?WSDL")
public class BdxService
    extends Service
{

    private final static URL BDXSERVICE_WSDL_LOCATION;
    private final static WebServiceException BDXSERVICE_EXCEPTION;
    private final static QName BDXSERVICE_QNAME = new QName("http://tempuri.org/", "BdxService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://183.129.144.67:8017/BdxWebService/BdxService.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BDXSERVICE_WSDL_LOCATION = url;
        BDXSERVICE_EXCEPTION = e;
    }

    public BdxService() {
        super(__getWsdlLocation(), BDXSERVICE_QNAME);
    }

    public BdxService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BDXSERVICE_QNAME, features);
    }

    public BdxService(URL wsdlLocation) {
        super(wsdlLocation, BDXSERVICE_QNAME);
    }

    public BdxService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BDXSERVICE_QNAME, features);
    }

    public BdxService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BdxService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BdxServiceSoap
     */
    @WebEndpoint(name = "BdxServiceSoap")
    public BdxServiceSoap getBdxServiceSoap() {
        return super.getPort(new QName("http://tempuri.org/", "BdxServiceSoap"), BdxServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BdxServiceSoap
     */
    @WebEndpoint(name = "BdxServiceSoap")
    public BdxServiceSoap getBdxServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "BdxServiceSoap"), BdxServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BDXSERVICE_EXCEPTION!= null) {
            throw BDXSERVICE_EXCEPTION;
        }
        return BDXSERVICE_WSDL_LOCATION;
    }

}
