
package com.zxtech.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BdxServiceSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BdxServiceSoap {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetFilialeDepot", action = "http://tempuri.org/GetFilialeDepot")
    @WebResult(name = "GetFilialeDepotResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetFilialeDepot", targetNamespace = "http://tempuri.org/", className = "com.zxtech.ws.GetFilialeDepot")
    @ResponseWrapper(localName = "GetFilialeDepotResponse", targetNamespace = "http://tempuri.org/", className = "com.zxtech.ws.GetFilialeDepotResponse")
    public String getFilialeDepot();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetAgreementExplain", action = "http://tempuri.org/GetAgreementExplain")
    @WebResult(name = "GetAgreementExplainResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetAgreementExplain", targetNamespace = "http://tempuri.org/", className = "com.zxtech.ws.GetAgreementExplain")
    @ResponseWrapper(localName = "GetAgreementExplainResponse", targetNamespace = "http://tempuri.org/", className = "com.zxtech.ws.GetAgreementExplainResponse")
    public String getAgreementExplain();

    /**
     * 
     * @param depotName
     * @param itemCode
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetItemStockQty", action = "http://tempuri.org/GetItemStockQty")
    @WebResult(name = "GetItemStockQtyResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetItemStockQty", targetNamespace = "http://tempuri.org/", className = "com.zxtech.ws.GetItemStockQty")
    @ResponseWrapper(localName = "GetItemStockQtyResponse", targetNamespace = "http://tempuri.org/", className = "com.zxtech.ws.GetItemStockQtyResponse")
    public String getItemStockQty(
        @WebParam(name = "ItemCode", targetNamespace = "http://tempuri.org/")
        String itemCode,
        @WebParam(name = "DepotName", targetNamespace = "http://tempuri.org/")
        String depotName);

    /**
     * 
     * @param customerName
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetCustomer", action = "http://tempuri.org/GetCustomer")
    @WebResult(name = "GetCustomerResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetCustomer", targetNamespace = "http://tempuri.org/", className = "com.zxtech.ws.GetCustomer")
    @ResponseWrapper(localName = "GetCustomerResponse", targetNamespace = "http://tempuri.org/", className = "com.zxtech.ws.GetCustomerResponse")
    public String getCustomer(
        @WebParam(name = "CustomerName", targetNamespace = "http://tempuri.org/")
        String customerName);

    /**
     * 
     * @param itemCode
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetItem", action = "http://tempuri.org/GetItem")
    @WebResult(name = "GetItemResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetItem", targetNamespace = "http://tempuri.org/", className = "com.zxtech.ws.GetItem")
    @ResponseWrapper(localName = "GetItemResponse", targetNamespace = "http://tempuri.org/", className = "com.zxtech.ws.GetItemResponse")
    public String getItem(
        @WebParam(name = "ItemCode", targetNamespace = "http://tempuri.org/")
        String itemCode);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetFetchProperty", action = "http://tempuri.org/GetFetchProperty")
    @WebResult(name = "GetFetchPropertyResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetFetchProperty", targetNamespace = "http://tempuri.org/", className = "com.zxtech.ws.GetFetchProperty")
    @ResponseWrapper(localName = "GetFetchPropertyResponse", targetNamespace = "http://tempuri.org/", className = "com.zxtech.ws.GetFetchPropertyResponse")
    public String getFetchProperty();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetFetchType", action = "http://tempuri.org/GetFetchType")
    @WebResult(name = "GetFetchTypeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetFetchType", targetNamespace = "http://tempuri.org/", className = "com.zxtech.ws.GetFetchType")
    @ResponseWrapper(localName = "GetFetchTypeResponse", targetNamespace = "http://tempuri.org/", className = "com.zxtech.ws.GetFetchTypeResponse")
    public String getFetchType();

    /**
     * 
     * @param billXml
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ImpPartRequireBill", action = "http://tempuri.org/ImpPartRequireBill")
    @WebResult(name = "ImpPartRequireBillResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ImpPartRequireBill", targetNamespace = "http://tempuri.org/", className = "com.zxtech.ws.ImpPartRequireBill")
    @ResponseWrapper(localName = "ImpPartRequireBillResponse", targetNamespace = "http://tempuri.org/", className = "com.zxtech.ws.ImpPartRequireBillResponse")
    public String impPartRequireBill(
        @WebParam(name = "billXml", targetNamespace = "http://tempuri.org/")
        String billXml);

}
