
package com.sinyd.allen.test;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "TestWebServiceSoap", targetNamespace = "http://www.sinyd.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TestWebServiceSoap {


    /**
     * 
     * @param sex
     * @param name
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "HelloWorld", action = "http://www.sinyd.com/HelloWorld")
    @WebResult(name = "HelloWorldResult", targetNamespace = "http://www.sinyd.com/")
    @RequestWrapper(localName = "HelloWorld", targetNamespace = "http://www.sinyd.com/", className = "com.sinyd.allen.test.HelloWorld")
    @ResponseWrapper(localName = "HelloWorldResponse", targetNamespace = "http://www.sinyd.com/", className = "com.sinyd.allen.test.HelloWorldResponse")
    public String helloWorld(
        @WebParam(name = "name", targetNamespace = "http://www.sinyd.com/")
        String name,
        @WebParam(name = "sex", targetNamespace = "http://www.sinyd.com/")
        String sex);

}
