
package com.sinyd.allen.test;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "TestWebService", targetNamespace = "http://www.sinyd.com/", wsdlLocation = "http://192.168.1.178/TestWebService/TestWebService.asmx?WSDL")
public class TestWebService
    extends Service
{

    private final static URL TESTWEBSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.sinyd.allen.test.TestWebService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.sinyd.allen.test.TestWebService.class.getResource(".");
            url = new URL(baseUrl, "http://192.168.1.178/TestWebService/TestWebService.asmx?WSDL");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://192.168.1.178/TestWebService/TestWebService.asmx?WSDL', retrying as a local file");
            logger.warning(e.getMessage());
        }
        TESTWEBSERVICE_WSDL_LOCATION = url;
    }

    public TestWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TestWebService() {
        super(TESTWEBSERVICE_WSDL_LOCATION, new QName("http://www.sinyd.com/", "TestWebService"));
    }

    /**
     * 
     * @return
     *     returns TestWebServiceSoap
     */
    @WebEndpoint(name = "TestWebServiceSoap")
    public TestWebServiceSoap getTestWebServiceSoap() {
        return super.getPort(new QName("http://www.sinyd.com/", "TestWebServiceSoap"), TestWebServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TestWebServiceSoap
     */
    @WebEndpoint(name = "TestWebServiceSoap")
    public TestWebServiceSoap getTestWebServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.sinyd.com/", "TestWebServiceSoap"), TestWebServiceSoap.class, features);
    }

}
